# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='pub_date')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='update_date')),
            ],
        ),
    ]
